// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function fail(param) {
  return Curry._1((() => { throw "rescript-mpst-fail"; }), undefined);
}

function dontknow(param) {
  return null;
}

function assertfalse(param) {
  return Curry._1((() => { throw "rescript-mpst-assert-false"}), undefined);
}

function todo(param) {
  return Curry._1((() => { throw "rescript-mpst-todo"; }), undefined);
}

function make_polyvar(tag, v) {
  return ((tag, v) => ({"NAME":tag, "VAL":v}))(tag, v);
}

function destruct_polyvar($$var) {
  return ((var_) => ([var_.NAME, var_.VAL]))($$var);
}

export {
  fail ,
  dontknow ,
  assertfalse ,
  todo ,
  make_polyvar ,
  destruct_polyvar ,
  
}
/* No side effect */
