// Generated by ReScript, PLEASE EDIT WITH CARE


function raw_send(mpchan, role, label, v) {
  var msg = {
    to_username: role,
    content: [
      label,
      v
    ]
  };
  mpchan.emit("message from browser", msg);
  
}

function raw_receive(mpchan, role) {
  return new Promise((function (resolve, _reject) {
                var message = function (params) {
                  var content_message = params.content;
                  return resolve([
                              content_message[0],
                              content_message[1]
                            ]);
                };
                mpchan.on("message from " + role, message);
                
              }));
}

export {
  raw_send ,
  raw_receive ,
  
}
/* No side effect */
