// Generated by ReScript, PLEASE EDIT WITH CARE


var imai = {
  name: "Keigo Imai",
  address: "Nagoya"
};

function raw_send(mpchan, role, label, v) {
  var msg = {
    to_username: "username",
    content: "hello"
  };
  mpchan.emit("message from browser", msg);
  
}

function raw_receive(mpchan, role) {
  return new Promise((function (resolve, _reject) {
                var message = function (params) {
                  console.log("got a message from" + params.from_username + ", content:" + params.content);
                  
                };
                mpchan.on("message from server", message);
                
              }));
}

export {
  imai ,
  raw_send ,
  raw_receive ,
  
}
/* No side effect */
