// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Mpst$TravelAgency from "./mpst/Mpst.js";
import * as Protocol$TravelAgency from "./Protocol.js";

function Agency(Props) {
  var onclick = function (_e) {
    var ch = Mpst$TravelAgency.connect(Protocol$TravelAgency.g, Protocol$TravelAgency.agency, "http://localhost:3050");
    Mpst$TravelAgency.receive(ch, (function (x) {
              return {
                      NAME: "Service",
                      VAL: x
                    };
            })).then(function (param) {
          var match = param.VAL;
          console.log("agency: I got: " + match[0]);
          return Mpst$TravelAgency.send(match[1], (function (x) {
                        return {
                                NAME: "Customer",
                                VAL: x
                              };
                      }), (function (x) {
                        return {
                                NAME: "response",
                                VAL: x
                              };
                      }), "billing");
        });
    console.log("msg2");
    
  };
  return React.createElement("button", {
              onClick: onclick
            }, "agency");
}

var make = Agency;

var $$default = Agency;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
