// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Agency$TravelAgency from "./Agency.js";
import * as Service$TravelAgency from "./Service.js";
import * as Customer$TravelAgency from "./Customer.js";

import './App.css';
;

function App(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setuser = match[1];
  var user = match[0];
  var onclickC = function (_e) {
    return Curry._1(setuser, (function (param) {
                  return "customer";
                }));
  };
  var onclickS = function (_e) {
    return Curry._1(setuser, (function (param) {
                  return "service";
                }));
  };
  var onclickA = function (_e) {
    return Curry._1(setuser, (function (param) {
                  return "agency";
                }));
  };
  return React.createElement("div", {
              className: "App"
            }, user === "" ? React.createElement("div", undefined, React.createElement("div", undefined, "No user"), React.createElement("button", {
                        onClick: onclickC
                      }, "Customer"), React.createElement("button", {
                        onClick: onclickS
                      }, "Service"), React.createElement("button", {
                        onClick: onclickA
                      }, "Agency")) : React.createElement("div", undefined), user === "customer" ? React.createElement(Customer$TravelAgency.make, {}) : React.createElement("div", undefined), user === "service" ? React.createElement(Service$TravelAgency.make, {}) : React.createElement("div", undefined), user === "agency" ? React.createElement(Agency$TravelAgency.make, {}) : React.createElement("div", undefined));
}

var make = App;

var $$default = App;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
