// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Mpst$TravelAgency from "./mpst/Mpst.js";
import * as Protocol$TravelAgency from "./Protocol.js";

function Hotel(Props) {
  var onclick = function (_e) {
    var ch = Mpst$TravelAgency.connect(Protocol$TravelAgency.g, Protocol$TravelAgency.hotel, "http://localhost:3050");
    Mpst$TravelAgency.receive(ch, (function (x) {
              return {
                      NAME: "Agency",
                      VAL: x
                    };
            })).then(function (ret) {
          return Mpst$TravelAgency.close(ret.NAME === "quote" ? ret.VAL[1] : Mpst$TravelAgency.send(ret.VAL[1], (function (x) {
                              return {
                                      NAME: "Customer",
                                      VAL: x
                                    };
                            }), (function (x) {
                              return {
                                      NAME: "billing",
                                      VAL: x
                                    };
                            }), "bbb"));
        });
    console.log("msg2");
    
  };
  return React.createElement("button", {
              onClick: onclick
            }, "hotel");
}

var make = Hotel;

var $$default = Hotel;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
