// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Raw$TravelAgency from "./mpst/Raw.js";
import * as Mpst$TravelAgency from "./mpst/Mpst.js";

function lens_c_get(param) {
  return param[2];
}

function lens_c_put(param, c) {
  return [
          param[0],
          param[1],
          c
        ];
}

var lens_c = {
  get: lens_c_get,
  put: lens_c_put
};

function lens_s_get(param) {
  return param[1];
}

function lens_s_put(param, s) {
  return [
          param[0],
          s,
          param[2]
        ];
}

var lens_s = {
  get: lens_s_get,
  put: lens_s_put
};

function lens_a_get(param) {
  return param[0];
}

function lens_a_put(param, a) {
  return [
          a,
          param[1],
          param[2]
        ];
}

var lens_a = {
  get: lens_a_get,
  put: lens_a_put
};

var customer_role_label = {
  closed_match: (function (param) {
      return param.VAL;
    }),
  closed_make: (function (v) {
      return {
              NAME: "Customer",
              VAL: v
            };
    })
};

var customer = {
  role_label: customer_role_label,
  role_lens: lens_c
};

var service_role_label = {
  closed_match: (function (param) {
      return param.VAL;
    }),
  closed_make: (function (v) {
      return {
              NAME: "Service",
              VAL: v
            };
    })
};

var service = {
  role_label: service_role_label,
  role_lens: lens_s
};

var agency_role_label = {
  closed_match: (function (param) {
      return param.VAL;
    }),
  closed_make: (function (v) {
      return {
              NAME: "Agency",
              VAL: v
            };
    })
};

var agency = {
  role_label: agency_role_label,
  role_lens: lens_a
};

function reserve_or_cancel_concat(l, r) {
  return {
          hd: {
            NAME: "reserve",
            VAL: Mpst$TravelAgency.list_match((function (param) {
                    return param.VAL;
                  }), l)
          },
          tl: {
            hd: {
              NAME: "cancel",
              VAL: Mpst$TravelAgency.list_match((function (param) {
                      return param.VAL;
                    }), r)
            },
            tl: /* [] */0
          }
        };
}

function reserve_or_cancel_split(lr) {
  return [
          {
            hd: {
              NAME: "reserve",
              VAL: Mpst$TravelAgency.list_match((function (x) {
                      if (x.NAME === "cancel") {
                        return Raw$TravelAgency.dontknow(undefined);
                      } else {
                        return x.VAL;
                      }
                    }), lr)
            },
            tl: /* [] */0
          },
          {
            hd: {
              NAME: "cancel",
              VAL: Mpst$TravelAgency.list_match((function (x) {
                      if (x.NAME === "cancel") {
                        return x.VAL;
                      } else {
                        return Raw$TravelAgency.dontknow(undefined);
                      }
                    }), lr)
            },
            tl: /* [] */0
          }
        ];
}

var reserve_or_cancel = {
  concat: reserve_or_cancel_concat,
  split: reserve_or_cancel_split
};

var price_label_closed = {
  closed_match: (function (param) {
      return param.VAL;
    }),
  closed_make: (function (v) {
      return {
              NAME: "price",
              VAL: v
            };
    })
};

function price_label_open(v) {
  return {
          NAME: "price",
          VAL: v
        };
}

var price = {
  label_closed: price_label_closed,
  label_open: price_label_open
};

var customer_option_label_closed = {
  closed_match: (function (param) {
      return param.VAL;
    }),
  closed_make: (function (v) {
      return {
              NAME: "customer_option",
              VAL: v
            };
    })
};

function customer_option_label_open(v) {
  return {
          NAME: "customer_option",
          VAL: v
        };
}

var customer_option = {
  label_closed: customer_option_label_closed,
  label_open: customer_option_label_open
};

var response_label_closed = {
  closed_match: (function (param) {
      return param.VAL;
    }),
  closed_make: (function (v) {
      return {
              NAME: "response",
              VAL: v
            };
    })
};

function response_label_open(v) {
  return {
          NAME: "response",
          VAL: v
        };
}

var response = {
  label_closed: response_label_closed,
  label_open: response_label_open
};

var g = Mpst$TravelAgency.$neg$neg$great(customer, service, price, Mpst$TravelAgency.$neg$neg$great(service, agency, customer_option, Mpst$TravelAgency.$neg$neg$great(agency, customer, response, Mpst$TravelAgency.finish)));

export {
  lens_c ,
  lens_s ,
  lens_a ,
  customer ,
  service ,
  agency ,
  reserve_or_cancel ,
  price ,
  customer_option ,
  response ,
  g ,
  
}
/* g Not a pure module */
