// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SocketIoClient from "socket.io-client";

function Service(Props) {
  var myURL = new URL("http://localhost:3050");
  var socket = SocketIoClient.io(myURL, {
        autoConnect: false
      });
  var onclick = function (_e) {
    console.log("msg");
    socket.auth = {
      username: "service"
    };
    socket.connect();
    socket.emit("message from browser", {
          to_username: "agency",
          content: "hello"
        });
    socket.on("message from server", (function (params) {
            console.log("got a message from" + params.from_username + ", content:" + params.content);
            
          }));
    console.log("msg2");
    
  };
  return React.createElement("button", {
              onClick: onclick
            }, "service");
}

var make = Service;

var $$default = Service;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
