// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Mpst$TravelAgency from "./mpst/Mpst.js";
import * as Protocol$TravelAgency from "./Protocol.js";

function Service(Props) {
  var onclick = function (_e) {
    var ch = Mpst$TravelAgency.connect(Protocol$TravelAgency.g, Protocol$TravelAgency.service, "http://localhost:3050");
    Mpst$TravelAgency.receive(ch, (function (x) {
              return {
                      NAME: "Customer",
                      VAL: x
                    };
            })).then(function (param) {
          var match = param.VAL;
          console.log("service: I got: " + match[0]);
          return Mpst$TravelAgency.send(match[1], (function (x) {
                        return {
                                NAME: "Agency",
                                VAL: x
                              };
                      }), (function (x) {
                        return {
                                NAME: "customer_option",
                                VAL: x
                              };
                      }), "option");
        });
    console.log("msg2");
    
  };
  return React.createElement("button", {
              onClick: onclick
            }, "service");
}

var make = Service;

var $$default = Service;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
